VIETNAMESE_LABELS = {
    'DP.135': 'Het tat ca lenh cam', 'P.102': 'Cam di nguoc chieu', 'P.103a': 'Cam o to',
    'P.103b': 'Cam o to re phai', 'P.103c': 'Cam o to re trai', 'P.104': 'Cam mo to',
    'P.106a': 'Cam xe tai', 'P.106b': 'Cam xe tai tren 2.5T', 'P.107a': 'Cam o to khach va tai',
    'P.112': 'Cam nguoi di bo', 'P.115': 'Han che trong luong xe', 'P.117': 'Han che chieu cao',
    'P.123a': 'Cam re trai', 'P.123b': 'Cam re phai', 'P.124a': 'Cam quay dau',
    'P.124b': 'Cam o to quay dau', 'P.124c': 'Cam re trai va quay dau', 'P.125': 'Cam vuot',
    'P.127': 'Toc do toi da cho phep', 'P.128': 'Cam bop coi', 'P.130': 'Cam dung va do xe',
    'P.131a': 'Cam do xe', 'P.137': 'Cam re trai va re phai', 'P.245a': 'Di cham',
    'R.301c': 'Re trai', 'R.301d': 'Re phai', 'R.301e': 'Re trai hoac phai',
    'R.302a': 'Huong phai vong sang phai', 'R.302b': 'Huong phai vong sang trai',
    'R.303': 'Vong xuyen', 'R.407a': 'Duong mot chieu', 'R.409': 'Cho quay dau xe',
    'R.425': 'Duong danh cho o to', 'R.434': 'Ben xe buyt', 'S.509a': 'Chieu cao an toan',
    'W.201a': 'Ngoat ben trai nguy hiem', 'W.201b': 'Ngoat ben phai nguy hiem',
    'W.202a': 'Nhieu cho ngoat (trai truoc)', 'W.202b': 'Nhieu cho ngoat (phai truoc)',
    'W.203b': 'Duong hep ben trai', 'W.203c': 'Duong hep ben phai', 'W.205a': 'Giao nhau duong cung cap',
    'W.205b': 'Giao nhau duong cung cap', 'W.205d': 'Giao nhau duong cung cap',
    'W.207a': 'Giao voi duong khong uu tien', 'W.207b': 'Giao voi duong khong uu tien',
    'W.207c': 'Giao voi duong khong uu tien', 'W.208': 'Giao voi duong uu tien',
    'W.209': 'Giao nhau co den tin hieu', 'W.210': 'Giao voi duong sat co rao',
    'W.219': 'Doc xuong nguy hiem', 'W.221b': 'Duong khong bang phang',
    'W.224': 'Nguoi di bo cat ngang', 'W.225': 'Tre em cat ngang', 'W.227': 'Cong truong',
    'W.233': 'Nguy hiem khac', 'W.235': 'Duong doi', 'W.245a': 'Di cham'
}
